#ifndef VEHICLEMULTIMEDIATYPE_H
#define VEHICLEMULTIMEDIATYPE_H

enum class VehicleMultimedia
{
    ANALOG,
    ANDROID_SMART,
    APPLE_ANDROID_SMART,
    APPLE_SMART
};

#endif // VEHICLEMULTIMEDIATYPE_H
